language: elixir

elixir:
  - 1.2.6
  - 1.3.4

otp_release:
  - 18.3
  - 19.2

before_install:
  - sudo apt-get update -qq
  - ./test/build.sh

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
