language: elixir

elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6

otp_release:
  - 18.3
  - 19.3
  - 20.3

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.3
    - elixir: 1.4
      otp_release: 20.3

env:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle ES_JAVA_OPTS="-Xms128m -Xmx128m"

before_install:
  - sudo service elasticsearch stop &&
    sudo add-apt-repository -y ppa:webupd8team/java &&
    sudo apt-get update -qq &&
    sudo apt-get install -y oracle-java8-installer oracle-java8-set-default

  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.0.tar.gz &&
    tar zxvf elasticsearch-5.3.0.tar.gz

  - cp -pR elasticsearch-5.3.0 /tmp/9200 &&
    cp -pR elasticsearch-5.3.0 /tmp/9201 &&
    cp -pR elasticsearch-5.3.0 /tmp/9202

  - "sed -i -e 's/#http.port: 9200/http.port: 9200/g' /tmp/9200/config/elasticsearch.yml"
  - "sed -i -e 's/#http.port: 9200/http.port: 9201/g' /tmp/9201/config/elasticsearch.yml"
  - "sed -i -e 's/#http.port: 9200/http.port: 9202/g' /tmp/9202/config/elasticsearch.yml"

  - yes | /tmp/9200/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-kuromoji-neologd:5.2.1 &&
    yes | /tmp/9201/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-kuromoji-neologd:5.2.1 &&
    yes | /tmp/9202/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-kuromoji-neologd:5.2.1

  # - ((sh /tmp/9200/bin/elasticsearch) &) &> /dev/null
  # - ESPID1=$!

  # - ((sh /tmp/9201/bin/elasticsearch) &) &> /dev/null
  # - ESPID2=$!

  # - ((sh /tmp/9202/bin/elasticsearch) &) &> /dev/null
  # - ESPID3=$!

  - /tmp/9200/bin/elasticsearch &
  - ESPID1=$!

  - /tmp/9201/bin/elasticsearch &
  - ESPID2=$!

  - /tmp/9202/bin/elasticsearch &
  - ESPID3=$!

script:
  - yes | mix do deps.get
  - yes | MIX_ENV=test mix test
  - curl 'localhost:9200/_nodes/process?pretty'
  - curl 'localhost:9201/_nodes/process?pretty'

after_script:
  - kill $ESPID1
         $ESPID2
         $ESPID3

  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
